name: GitHub Actions Demo

on: 
  push:
    branches:
      - main
    paths-ignore:
      - ".github/**"
  pull_request:
    branches: 
      - main
  schedule:
    - cron: "15 6 * * 0"
  workflow_dispatch:

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Display Event Name
        run: echo "event name is:" ${{ github.event_name }}
      - name: Display Ref Branch Name
        run: echo "ref branch name is:" ${{ github.ref }}
      - uses: actions/checkout@v4
      - name: Display Files in ${{ github.ref }} branch
        run: tree
